version: "3"

networks:
  backend:

services:
  db:
    image: "mcr.microsoft.com/mssql/server:2017-latest"
    environment:
      SA_PASSWORD: "OpenSim123"
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Enterprise"
    networks:
      - backend

  api_with_app:
    build: 
      context: .
      dockerfile: Dockerfile.api
    depends_on:
      - db
    networks:
      - backend
    ports:
      - 3000:80

#  enable after FE / BE separation
#  api:
#    build: 
#      context: .
#      dockerfile: Dockerfile.Api
#    depends_on:
#      - db
#    networks:
#      - backend
#    ports:
#      - 3000:80

#  app:
#    build:
#      context: .
#      dockerfile: Dockerfile.App
#    ports:
#      - 4200:4200
    