FROM microsoft/dotnet:2.2-aspnetcore-runtime

COPY dist /app

COPY entrypoint.sh /app/entrypoint.sh

WORKDIR /app

RUN apt-get update -yq && apt-get upgrade -yq && apt-get install -yq curl git nano
RUN curl -sL https://deb.nodesource.com/setup_8.x | bash - && apt-get install -yq nodejs build-essential
RUN npm install -g npm
RUN npm install -g @angular/cli

EXPOSE 80/tcp

ENTRYPOINT ["dotnet", "OpenSim.Portal.dll"]

RUN chmod +x ./entrypoint.sh
CMD /bin/bash ./entrypoint.sh