version: "3"

networks:
  backend:
  frontend:

services:
  db:
    image: "mcr.microsoft.com/mssql/server:2017-latest"
    environment:
      SA_PASSWORD: "OpenSim123"
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Enterprise"
    networks:
      - backend

#  api_with_app:
#    build: 
#      context: .
#      dockerfile: Dockerfile
#    depends_on:
#      - db
#    networks:
#      - backend
#    ports:
#      - 3000:80

  api:
    build: 
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    networks:
      - backend
      - frontend
 #   ports:
 #     - 3000:80

  app:
    build:
      context: ./ClientApp
      dockerfile: Dockerfile
    depends_on:
      - api
    networks:
      - frontend
    ports:
      - 4200:80
    