version: "3"

networks:
  backend:

volumes:
  sqldata:

services:
  db:
    image: "mcr.microsoft.com/mssql/server:2017-latest"
    environment:
      SA_PASSWORD: "OpenSim123"
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Enterprise"
    networks:
      - backend
    volumes:
      - sqldata:/var/opt/mssql

  api:
    image: kirsar/portal_api:latest
    depends_on:
      - db
    networks:
      - backend
    ports:
      - 3000:80

  app:
    image: kirsar/portal_app:latest
    depends_on:
      - api
    ports:
      - 80:80
    